[package]
name = "protocol"
version.workspace = true
edition.workspace = true

[dependencies]
bytes.workspace = true
thiserror.workspace = true
macros.workspace = true
async-trait.workspace = true
log.workspace = true
components.workspace = true
serde.workspace = true
serde_json.workspace = true
